MODEL:
  NAME: 'resnet50_ifn'
  LAST_STRIDE: 1
  POOL: "MAX"

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  HF_PROB: 0.5 # random horizontal flip
  PADDING: 10

  RE: False # enable random erasing
  RE_PROB: 0.5 # random erasing probability

DATASETS:
  SOURCE: ['Market-1501', 'DukeMTMC-reID', 'CUHK03', 'CUHK02', 'CUHK-SYSU']
  TARGET: ['MSMT17_V2']
  # STORE_DIR: './datasets'
  # STORE_DIR: '/Users/linshan/Pictures/Person_ReID_Datasets'
  STORE_DIR: '../dsta/Datasets'

DATALOADER:
  NUM_WORKERS: 8

SOLVER:
  LOSS: 'softmax'

  SCHED: "WarmupMultiStepLR"
  WARMUP_STEPS: [40, 70]
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'
  
  MAX_EPOCHS: 160
  IMS_PER_BATCH: 64

  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 256
  LOAD_EPOCH: 160

OUTPUT_DIR: "./checkpoint/Dual_Norm_31_S1"
# DEVICE: "cpu"
DEVICE: "cuda:0"
