DATALOADER:
  NUM_INSTANCE: 32
  NUM_WORKERS: 8
DATASETS:
  MERGE: True
  SOURCE: ['Market-1501']
  STORE_DIR: /home/GTA
  # TARGET: ['NTUOutdoorv2_black', 'NTUOutdoorv2_white']
  TARGET: ['Market-1501']
DEVICE: 'cuda:6'
INPUT:
  BRIGHTNESS: [1.0, 1.0]
  CONTRAST: 0.0
  HF_PROB: 0.5
  HUE: 0.0
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  RE: False
  RE_PROB: 0.5
  SATURATION: 0.0
  SIZE_TEST: [384, 128]
  SIZE_TRAIN: [384, 128]
MODEL:
  CLASS_PARAM: 1.0
  D_PARAM: 1.0
  G_PARAM: 1.0
  LAST_STRIDE: 2
  NAME: 'resnet50_ifn'
  POOL: 'AVG'
OUTPUT_DIR: ./checkpoint/Market-1501/dual_norm_384x128
RE_RANKING: False
SOLVER:
  LOSS: 'softmax'
  MAX_EPOCHS: 160
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 10
TEST:
  IMS_PER_BATCH: 1
  LOAD_EPOCH: 160